// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: pkMsg.proto

package pkMsgpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PkMsgHandleClient is the client API for PkMsgHandle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PkMsgHandleClient interface {
	// Handles a received PkMsg message
	PkMsgReceive(ctx context.Context, in *PkMsg, opts ...grpc.CallOption) (*PkMsgResponse, error)
}

type pkMsgHandleClient struct {
	cc grpc.ClientConnInterface
}

func NewPkMsgHandleClient(cc grpc.ClientConnInterface) PkMsgHandleClient {
	return &pkMsgHandleClient{cc}
}

func (c *pkMsgHandleClient) PkMsgReceive(ctx context.Context, in *PkMsg, opts ...grpc.CallOption) (*PkMsgResponse, error) {
	out := new(PkMsgResponse)
	err := c.cc.Invoke(ctx, "/pkMsgpb.PkMsgHandle/PkMsgReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PkMsgHandleServer is the server API for PkMsgHandle service.
// All implementations must embed UnimplementedPkMsgHandleServer
// for forward compatibility
type PkMsgHandleServer interface {
	// Handles a received PkMsg message
	PkMsgReceive(context.Context, *PkMsg) (*PkMsgResponse, error)
	mustEmbedUnimplementedPkMsgHandleServer()
}

// UnimplementedPkMsgHandleServer must be embedded to have forward compatible implementations.
type UnimplementedPkMsgHandleServer struct {
}

func (UnimplementedPkMsgHandleServer) PkMsgReceive(context.Context, *PkMsg) (*PkMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PkMsgReceive not implemented")
}
func (UnimplementedPkMsgHandleServer) mustEmbedUnimplementedPkMsgHandleServer() {}

// UnsafePkMsgHandleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PkMsgHandleServer will
// result in compilation errors.
type UnsafePkMsgHandleServer interface {
	mustEmbedUnimplementedPkMsgHandleServer()
}

func RegisterPkMsgHandleServer(s grpc.ServiceRegistrar, srv PkMsgHandleServer) {
	s.RegisterService(&PkMsgHandle_ServiceDesc, srv)
}

func _PkMsgHandle_PkMsgReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PkMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkMsgHandleServer).PkMsgReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkMsgpb.PkMsgHandle/PkMsgReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkMsgHandleServer).PkMsgReceive(ctx, req.(*PkMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// PkMsgHandle_ServiceDesc is the grpc.ServiceDesc for PkMsgHandle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PkMsgHandle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkMsgpb.PkMsgHandle",
	HandlerType: (*PkMsgHandleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PkMsgReceive",
			Handler:    _PkMsgHandle_PkMsgReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkMsg.proto",
}
