// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: pkMsg.proto

package pkMsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type PkMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   int64  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Pk     string `protobuf:"bytes,3,opt,name=pk,proto3" json:"pk,omitempty"`
	Sig    string `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *PkMsg) Reset() {
	*x = PkMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkMsg) ProtoMessage() {}

func (x *PkMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkMsg.ProtoReflect.Descriptor instead.
func (*PkMsg) Descriptor() ([]byte, []int) {
	return file_pkMsg_proto_rawDescGZIP(), []int{0}
}

func (x *PkMsg) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PkMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PkMsg) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

func (x *PkMsg) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type PkMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PkMsgResponse) Reset() {
	*x = PkMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkMsgResponse) ProtoMessage() {}

func (x *PkMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkMsgResponse.ProtoReflect.Descriptor instead.
func (*PkMsgResponse) Descriptor() ([]byte, []int) {
	return file_pkMsg_proto_rawDescGZIP(), []int{1}
}

var File_pkMsg_proto protoreflect.FileDescriptor

var file_pkMsg_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6b, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x6b, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x22, 0x55, 0x0a, 0x05, 0x50, 0x6b, 0x4d, 0x73, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x70,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x0f, 0x0a,
	0x0d, 0x50, 0x6b, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x47,
	0x0a, 0x0b, 0x50, 0x6b, 0x4d, 0x73, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x38, 0x0a,
	0x0c, 0x50, 0x6b, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x0e, 0x2e,
	0x70, 0x6b, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x50, 0x6b, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e,
	0x70, 0x6b, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x50, 0x6b, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x70, 0x6b,
	0x4d, 0x73, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkMsg_proto_rawDescOnce sync.Once
	file_pkMsg_proto_rawDescData = file_pkMsg_proto_rawDesc
)

func file_pkMsg_proto_rawDescGZIP() []byte {
	file_pkMsg_proto_rawDescOnce.Do(func() {
		file_pkMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkMsg_proto_rawDescData)
	})
	return file_pkMsg_proto_rawDescData
}

var file_pkMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkMsg_proto_goTypes = []interface{}{
	(*PkMsg)(nil),         // 0: pkMsgpb.PkMsg
	(*PkMsgResponse)(nil), // 1: pkMsgpb.PkMsgResponse
}
var file_pkMsg_proto_depIdxs = []int32{
	0, // 0: pkMsgpb.PkMsgHandle.PkMsgReceive:input_type -> pkMsgpb.PkMsg
	1, // 1: pkMsgpb.PkMsgHandle.PkMsgReceive:output_type -> pkMsgpb.PkMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkMsg_proto_init() }
func file_pkMsg_proto_init() {
	if File_pkMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkMsg_proto_goTypes,
		DependencyIndexes: file_pkMsg_proto_depIdxs,
		MessageInfos:      file_pkMsg_proto_msgTypes,
	}.Build()
	File_pkMsg_proto = out.File
	file_pkMsg_proto_rawDesc = nil
	file_pkMsg_proto_goTypes = nil
	file_pkMsg_proto_depIdxs = nil
}
